config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
    
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show, :destroy]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/register' => 'users#new'
  post '/register' => 'users#create'
  

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    authorize
  end

  def add_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 0 }
    item["quantity"] += 1
    cart[product_id] = item
    update_cart cart

    redirect_to :back
  end

  def remove_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 1 }
    item["quantity"] -= 1
    cart[product_id] = item
    cart.delete(product_id) if item["quantity"] < 1
    update_cart cart

    redirect_to :back
  end

end

app/views/carts/_item.html.erb
<% quantity = details['quantity'].to_i %>

<% if product = Product.find_by(id: product_id) %>
  <% item_total = product.price * quantity %>
  <% @cart_total += item_total %>

  <tr>
    <td>
      <%= image_tag product.image.tiny %>
    </td>
    <td>
      <h4><%= product.name %></h4>
      <br>
      <p><%= product.description %></p>
    </td>
    <td>
      <%= product.price %>
    </td>
    <td>
      <%= link_to remove_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-danger', method: :delete do %>
        -
      <% end %>
      <%= quantity %>
      <%= link_to add_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-success', method: :put do %>
        +
      <% end %>
    </td>
    <td>
      <%= item_total %>
    </td>
  </tr>
<% end %>

app/views/carts/show.html.erb
<section class="cart-show">
  <% if cart.size == 0 %>
    <h1>Your cart is empty.</h1>
    <br/>
    <%= link_to 'Return Home to Continue Shopping.', :root %>
  <% else %>
    <header class="page-header">
      <h1>My Cart</h1>
    </header>

    <div class="panel panel-default items">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th colspan="2">Product</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_total = 0 %>
          <% cart.each do |product_id, details| %>
            <%= render 'item', product_id: product_id, details: details %>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <th colspan="4">
              TOTAL:
            </th>
            <th>
              <%= @cart_total %>
            </th>
          </tr>
        </tfoot>
      </table>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= form_tag orders_path do %>
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-amount="<%= @cart_total * 100 %>"
            data-name="Jungle"
            data-description="Khurram Virani's Jungle Order"
            data-locale="auto"
            data-email="kvirani@gmail.com"
            data-currency="cad">
          </script>
        <% end %>
      </div>
    </div>
  <% end %>
</section>