config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
    
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show, :destroy]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/register' => 'users#new'
  post '/register' => 'users#create'
  

end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category
  has_many :reviews

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: ENV['ADMIN_USER'], password: ENV['ADMIN_PASSWORD']
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
    @reviews = @product.reviews.order(created_at: :desc)
    @average = Review.where(product_id: params[:id]).average(:rating)
  end

end

app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
      <%= image_tag product.image.thumb, alt: product.name %>
      <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <%= link_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary', method: :put do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>

  <% if product.quantity < 1 %>
    <aside class="sold-out"><strong>SOLD OUT!</strong></aside>
  <% end %>
</article>

app/views/products/_rating.html.erb
<div class="col-sm-8">
  <div class="well">
    <dl class="dl-horizontal">
      <% if current_user && current_user.id == review.user_id %>
        <span><%= link_to 'X', product_review_path(product_id: @product.id, id: review.id), class: "btn btn-danger", method: 'delete' %></span>
      <% end %>
      <h4>Product Rating: <%= review.rating %> out of 5<br/></h4>
      Created by <strong><%= review.user.first_name %></strong> about <%= time_ago_in_words(review.created_at) %> ago <br/><br/>
      <h5><%= review.description %></h5>
    </dl>
  </div>
</div>

app/views/products/_review.html.erb
<% if current_user %>
    <%= form_for :review, url: "#{@product.id}/reviews" do |f| %>
        <h2>Leave a Review:</h2>
        <textarea class="form-control" rows="3" <%= f.text_area :description %><br/></textarea>
        <%= f.select :rating, [1, 2, 3, 4, 5] %>
        <button type="submit" class="review btn btn-default"<%= f.submit "Submit" %>Sumbit Review</button>
    <% end %>
<% end %>

app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd><%= @product.price %></dd>
          <% if @average.to_i == 0 %>
          <h4><dt>Product Rating</dt>
            <dd>This product has not been rated yet.</dd></h4>
          <% else %>
          <h4><dt>Product Rating</dt>
            <dd><%= @average.to_i %> out of 5</dd></h4>
          <% end %>
        </dl>
      </div>
    </div>
    <%= render 'review' %>
      <h3 class="page-header"> Reviews: </h3>
      <br/>
      <% @reviews.each do |review| %>
        <%= render 'rating', review: review%>
    <% end %>
  </article>

</section>